export enum ActionType {
  AddBookToBookshelf = "ADD BOOK TO BOOKSHELF",
  AddTagToBook = "ADD TAG TO BOOK",
  AddCommentToBook = "ADD COMMENT TO BOOK",
  AddCommentToReview = "ADD COMMENT TO REVIEW",
  AddCommentToComment = "ADD COMMENT TO COMMENT",
  CreateBook = "CREATE BOOK",
  CreateBookshelf = "CREATE BOOKSHELF",
  CreateReview = "CREATE REVIEW",
  FollowUser = "FOLLOW USER",
  FollowTag = "FOLLOW TAG",
  ReactToComment = "REACT TO COMMENT",
  ReactToReview = "REACT TO REVIEW",
  UpvoteBook = "UPVOTE BOOK",
  UpvoteBookTag = "UPVOTE BOOK TAG",
  UpvoteComment = "UPVOTE COMMENT",
  UpvoteReview = "UPVOTE REVIEW",
}
